"""empty message

Revision ID: 29160c952541
Revises: 
Create Date: 2023-04-30 18:26:56.078578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29160c952541'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_usuario', sa.String(length=2), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ap_paterno', sa.String(length=100), nullable=False),
    sa.Column('ap_materno', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('estudiante_pdf', sa.String(length=255), nullable=True),
    sa.Column('cedula_profesional', sa.String(length=8), nullable=True),
    sa.Column('aprobado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
