"""empty message

Revision ID: 575e8039fc9d
Revises: c2c3f4da0159
Create Date: 2023-05-16 23:26:14.447163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575e8039fc9d'
down_revision = 'c2c3f4da0159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum',
    sa.Column('id_forum', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_inscription', sa.DateTime(), nullable=True),
    sa.Column('down', sa.Boolean(), nullable=True),
    sa.Column('down_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_forum')
    )
    op.create_table('publication',
    sa.Column('id_publication', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('born_date', sa.DateTime(), nullable=True),
    sa.Column('down_description', sa.Text(), nullable=True),
    sa.Column('forum_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['forum_id'], ['forum.id_forum'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_publication')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publication')
    op.drop_table('forum')
    # ### end Alembic commands ###
