"""empty message

Revision ID: 600fbfc19e36
Revises: 
Create Date: 2023-05-14 21:26:50.400172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600fbfc19e36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum',
    sa.Column('id_forum', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_inscription', sa.DateTime(), nullable=True),
    sa.Column('down', sa.Boolean(), nullable=True),
    sa.Column('down_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_forum')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_usuario', sa.String(length=2), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ap_paterno', sa.String(length=100), nullable=False),
    sa.Column('ap_materno', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('estudiante_pdf', sa.String(length=255), nullable=True),
    sa.Column('cedula_profesional', sa.String(length=8), nullable=True),
    sa.Column('aprobado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('publication',
    sa.Column('id_publication', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('born_date', sa.DateTime(), nullable=True),
    sa.Column('down_description', sa.Text(), nullable=True),
    sa.Column('forum_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['forum_id'], ['forum.id_forum'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_publication')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publication')
    op.drop_table('user')
    op.drop_table('forum')
    # ### end Alembic commands ###
