"""empty message

Revision ID: 713a789010ac
Revises: 5fdffcb19ef5
Create Date: 2023-05-14 14:52:28.014016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '713a789010ac'
down_revision = '5fdffcb19ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication',
    sa.Column('id_publication', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('born_date', sa.DateTime(), nullable=True),
    sa.Column('down_description', sa.Text(), nullable=True),
    sa.Column('forum_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['forum_id'], ['forum.id_forum'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_publication')
    )
    op.drop_table('publications')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publications',
    sa.Column('id_publication', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('born_date', mysql.DATETIME(), nullable=True),
    sa.Column('down_description', mysql.TEXT(), nullable=True),
    sa.Column('forum_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['forum_id'], ['forum.id_forum'], name='publications_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='publications_ibfk_2'),
    sa.PrimaryKeyConstraint('id_publication'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('publication')
    # ### end Alembic commands ###
